# While

# Loops

In [1]:
print('data science')
print('data science')
print('data science')
print('data science')
print('data science')

data science
data science
data science
data science
data science


In [1]:
i=1
while i>=1:
    print('data science')
    i=i-1

data science


In [3]:
i=1
while i<=5:
    print('data science')
    i=i+1

data science
data science
data science
data science
data science


In [4]:
i=1
while i>=1:
    print('data science:',i)
    i=i-1

data science: 1


In [5]:
i=5
while i>=1:
    print('data science:',i)
    i=i-1

data science: 5
data science: 4
data science: 3
data science: 2
data science: 1


In [6]:
i=1
while i<=5:
    print('data science')
    j=1
    while j<=4:
        print('technology')
        j=j+1
    i=i+1
    print()

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology

data science
technology
technology
technology
technology



In [6]:
i=1
while i<=5:
    print('data science', end=" ")
    j=1
    while j<=4:
        print('technology', end=" ")
        j=j+1
    i=i+1
    print()

data science technology technology technology technology 
data science technology technology technology technology 
data science technology technology technology technology 
data science technology technology technology technology 
data science technology technology technology technology 


In [9]:
i=1
while i <=2:
    j=0
    while j<=2:
        print(i*j,end="")
        j+=1
        print()
        i+=1

0
2
6


In [9]:
i=1
while i<=4:
    j=0
    while j<=3:
        print(i*j,end="")
        j+=1
        print()
        i+=1

0
2
6
12


# For Loop

In [10]:
name='nit'
for i in name:
    print(i)

n
i
t


In [11]:
name1=[1,3.5,'hallo']
for i in name1:
    print(i)

1
3.5
hallo


In [14]:
for i in [2,3,7.8,'hi']:
     print(i)

2
3
7.8
hi


In [15]:
range(5)

range(0, 5)

In [16]:
for i in range(5):
    print(i)

0
1
2
3
4


In [17]:
for i in range(2,5):
    print(i)

2
3
4


In [18]:
for i in range(1,10,3):
    print(i)

1
4
7


In [19]:
for i in range(1,21):
    print(i)
    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [21]:
for i in range(1,51):

    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [22]:
x=int(input('How many choclets you want:?'))
i=1
while i<=x:
    print('choclet')
    i+=1

How many choclets you want:? 3


choclet
choclet
choclet


In [23]:
ava=5
x=int(input('How many choclets you want:?'))
i=1
while i <=x:
    print('choclet')
    i+=1

How many choclets you want:? 5


choclet
choclet
choclet
choclet
choclet


In [24]:
avaliable_choclet=5
x=int(input('How many choclets user want:?'))
i=1
while i<=x:
    if i>avaliable_choclet:
        break
    print('choclet')
    i+=1
    print('bye for now')

How many choclets user want:? 6


choclet
bye for now
choclet
bye for now
choclet
bye for now
choclet
bye for now
choclet
bye for now


In [27]:
avaliable_choclet=5
x=int(input('How many choclets you want:?'))
i=1
while i<=x:
    if i>avaliable_choclet:
        print('out of stock')
        break
    print('choclet')
    i+=1
    print('bye for now')

How many choclets you want:? 10


choclet
bye for now
choclet
bye for now
choclet
bye for now
choclet
bye for now
choclet
bye for now
out of stock


In [28]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [29]:
for i in  range(1,11):
    if i ==3:
        continue
    print(i)

1
2
4
5
6
7
8
9
10


In [30]:
for i in range(1,11):
    if i == 3:
        continue 
    print(i)

1
2
4
5
6
7
8
9
10


In [31]:
for i in range(1,11):
    if i == 6:
        continue  
    print('hello :',i)    

hello : 1
hello : 2
hello : 3
hello : 4
hello : 5
hello : 7
hello : 8
hello : 9
hello : 10


In [11]:
for i in range(1,11):
    print('hallo')

hallo
hallo
hallo
hallo
hallo
hallo
hallo
hallo
hallo
hallo


In [12]:
for i in range(1,11):
    pass

In [34]:
for i in range(1,51):
    
    if i%3 == 0:
    
        print(i)
print('end')    

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [35]:
for i in range(1,51):
    
    if i%3 == 0:
        continue
    print(i)
print('end')    

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [36]:
for i in range(1,51):
    
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49


In [37]:
for i in range(1,50):
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)
print('end')    

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [38]:
for i in range(1,51):
    
    if (i%2 == 0):
        continue
    else:
        print(i)
print('bye')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
bye


In [1]:
for i in range(1,51):
    
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49


In [2]:
for i in range(1,50):
    if i%3 == 0 or i%5 == 0:
        continue
    print(i)
print('end')    

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [3]:
for i in range(1,51):
    
    if (i%2 == 0):
        #print('even')
        continue
    else:
        print(i)
print('bye')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
bye


In [4]:
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [13]:
for i in range(1,5):
    i=i+1
    print('# # # # ')

# # # # 
# # # # 
# # # # 
# # # # 


In [14]:
for i in range(1,5):
    if i<=5:
        print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [7]:
for j in range(4):
    print('#')

#
#
#
#


In [8]:
for j in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [9]:
for j in range(4):
    print('#', end = " ")

# # # # 

In [10]:
for j in range(4):
    print('#', end=" ")

for j in range(4):
    print('#', end=" ")


# # # # # # # # 

In [11]:
for j in range(4):
    print('#', end=" ")
    
print()
    
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 

In [12]:
for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

print()

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  

In [14]:
for i in range(4):
    for j in range(4):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  


In [15]:
for i in range(4):
    for j in range(i+1):
        print('#', end = " ")
    print()

# 
# # 
# # # 
# # # # 


In [16]:
for i in range(1,5):
    print("# "*i)

# 
# # 
# # # 
# # # # 


In [17]:
for i in range(1,5):
    for j in range(4):
        if i>j:
            print("#",end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [18]:
list(range(5))

[0, 1, 2, 3, 4]

In [19]:
for i in range(4):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  


In [20]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [21]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


In [22]:
for i in range(1,5):
    print("# "*(5-i))

# # # # 
# # # 
# # 
# 


# For else

In [23]:
nums = [12,15,18,21,26, 30, 40]

for num in nums:
    if num % 5 == 0:
        print(num)  

15
30
40


In [24]:
nums = [12,14,18,21,25,30,35]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
30
35


In [25]:
nums = [12,14,18,21,25,20]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
20


In [26]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [27]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [28]:
nums = [10,14,18,21,5,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

10


In [30]:
nums = [7,14,18,21,23,27] 

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

In [31]:
nums = [7,14,18,21,23,27,29] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found') #every iteration it cheking condition        

Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found


In [32]:
nums = [7,14] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found') 

Number Not Found
Number Not Found


In [33]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found')

Number Not Found


In [34]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [35]:
nums = [10,14,18,21,20,27,30] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
30
Not Found


In [36]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


# Prime Number

In [37]:
num = 14

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Not prime Number


In [38]:
num = 13

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Prime Number


# Array in python

In [39]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 3
Enter the next value 4
Enter the next value 5
Enter the next value 6
Enter the next value 7
Enter the next value 8


array('i', [4, 5, 6, 7, 8])


In [40]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 6
Enter the next value 7
Enter the next value 8
Enter the next value 04
Enter the next value 9
Enter the next value 6


array('i', [7, 8, 4, 9, 6])


In [4]:
from array import  *
arr = array('i',[])

n = input('Enter the length of the array')

for i in range(5):
    x = input('Enter the next value')
    
    arr.append(x)
print(arr)

Enter the length of the array 5
Enter the next value 6


TypeError: 'str' object cannot be interpreted as an integer

In [44]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [45]:
print(arr.dtype)

int64


In [46]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [47]:
print(arr.dtype)

float64


In [48]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [49]:
import numpy as np

In [50]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [51]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [52]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [53]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])

In [1]:
import tkinter as tk
# Function to be called when the button is clicked
def on_button_click():
    label.config(text="Button clicked!")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Hello, Tkinter!")
label.pack(pady=20)

# Create a button widget
button = tk.Button(root, text="Click Me", command=on_button_click)
button.pack(pady=20)

# Run the application
root.mainloop()

In [55]:
import tkinter as tk
from tkinter import messagebox

def on_button_click():
    user_input = entry.get()
    messagebox.showinfo("Information", f"You entered: {user_input}")

root = tk.Tk()
root.title("Simple Tkinter App")

label = tk.Label(root, text="Enter something:")
label.pack(pady=10)

entry = tk.Entry(root, width=30)
entry.pack(pady=10)

button = tk.Button(root, text="Submit", command=on_button_click)
button.pack(pady=10)

root.mainloop()


# 1.Right Angle Triangle Pattern

In [81]:
for i in range(1,6):
    print(' * '*i)

 * 
 *  * 
 *  *  * 
 *  *  *  * 
 *  *  *  *  * 


# 2.Inverted Right Angle Triangle Pattrn

In [80]:
for i in range(5,0,-1):
    print(' * '*i)

 *  *  *  *  * 
 *  *  *  * 
 *  *  * 
 *  * 
 * 


# 3.Pyramid Pattern 

In [77]:
for i in range (1,6):
    print(''*(5-i)+' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 


# 4.Inverted Pyramid Pattern

In [76]:
for i in range (5,0,-1):
    print(''*(5-i)+' * '*(2*i-1))

 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


# 5.Diamond Pattern

In [75]:
for i in range(1,6):
    print(''*(5-i)+' * '*(2*i-1))
for i in range(4,0,-1):
    print(''*(5-i)+' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


# 6.Hallow Square Pattern

In [73]:
for i in range(5):
    for j in range(5):
        if i==0 or i==4 or j==0 or j==4:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()

* * * * * 
*       * 
*       * 
*       * 
* * * * * 


# 7.Full Square Pattern

In [72]:
for i in range(5):
    print(' * '*5)

 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 


 # 8.Right Angle triangle(Number Pattern)

In [15]:
for i in range(5):
    print(''.join(str(x)for x in range(1,i+1)))


1
12
123
1234


# 9.Inverted Right Angle Triangle(Number Pattern)

In [71]:
for i in range(5,0,-1):
    print(' '.join(str(x)for x in range(1,i+1)))

1 2 3 4 5
1 2 3 4
1 2 3
1 2
1


# 10.Floyd's triangle

In [70]:
num=1
for i in range(1,6):
    for j in range(1,i+1):
        print(num,end=' ')
        num+=1
    print()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


# 11.Hallow Right Angle Triangle

In [69]:
for i in range(1,6):
    for j in range (1,i+1):
        if j==1 or j==i or i==5:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()

* 
* * 
*   * 
*     * 
* * * * * 


# 12.Hallow Pyramid Pattern

In [68]:
for i in range(1,6):
    for j in range(5-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j == 0 or j==2*i-2 or i==5:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()

        * 
      *   * 
    *       * 
  *           * 
* * * * * * * * * 


# 13.Hallow Diamond Pattern

In [64]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print('  ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()
    
for i in range(n-1,0,-1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()
    

            * 
         *   * 
      *       * 
   *           * 
*               * 
  *           * 
    *       * 
      *   * 
        * 


# 14.Hallow Diamond(Number Pattrn)

In [34]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(i,end=' ')
        else:
            print(' ',end=' ')
    print()

for i in range(n-1,0,-1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(i,end=' ')
        else:
            print(' ',end=' ')
    print()


        1 
      2   2 
    3       3 
  4           4 
5               5 
  4           4 
    3       3 
      2   2 
        1 


# 15.Butterfly Pattern

In [37]:
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
         print(j,end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(1,i+1):
        print(j,end=' ')
    print()
for i in range(n,0,-1):
    for j in range(1,i+1):
        print(j,end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(1,i+1):
        print(j,end=' ')
    print()

n=5
for i in range(1,n+1):
    for j in range(i):
        print('*',end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(i):
        print('*',end=' ')
    print()
for i in range(n,0,-1):
    for j in range(i):
        print('*',end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(i):
        print('*',end=' ')
    print()
        


1                 1 
1 2             1 2 
1 2 3         1 2 3 
1 2 3 4     1 2 3 4 
1 2 3 4 5 1 2 3 4 5 
1 2 3 4 5 1 2 3 4 5 
1 2 3 4     1 2 3 4 
1 2 3         1 2 3 
1 2             1 2 
1                 1 
*                 * 
* *             * * 
* * *         * * * 
* * * *     * * * * 
* * * * * * * * * * 
* * * * * * * * * * 
* * * *     * * * * 
* * *         * * * 
* *             * * 
*                 * 


# 16.Hallow Number Pyramid

In [43]:
n=5
for i in range(1, n + 1):
    for j in range(n - i):
        print(' ', end=' ')

    for j in range(1, 2 * i):
        if j == 1 or j == 2 * i - 1 or i == n:
            print(i,end=' ')
        else:
            print(' ', end =' ')
    print()

        1 
      2   2 
    3       3 
  4           4 
5 5 5 5 5 5 5 5 5 


# 17.Full Star Pyramid 

In [45]:
n=5
for i in range (1,n+1):
    for j in range(n-i):
        print(' ',end=' ')

    for j in range(2*i-1):
        print('*',end=' ')

    print()

        * 
      * * * 
    * * * * * 
  * * * * * * * 
* * * * * * * * * 


# 18.Inverted Full Star Pyramid

In [46]:
n=5
for i in range(n,0,-1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        print('*',end=' ')
    print()

* * * * * * * * * 
  * * * * * * * 
    * * * * * 
      * * * 
        * 


# `19.Left Aligned Pyramid Pattern

In [47]:
n=5
for i in range(1,n+1):
    for j in range (i):
        print('*',end=' ')
    print()
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j,end=' ')
    print()

* 
* * 
* * * 
* * * * 
* * * * * 
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


# 20.Right Aligned Pyramid Pattern

In [56]:
n=5
for i in range(1,n+1):
    
    for j in range(n-i):
        print(' ',end=' ')
        
    for j in range(1,i+1):
        print(j, end=' ')
        
    print()
n=5
for i in range(1,n+1):
    
    for j in range(n-i):
        print(' ',end=' ')
        
    for j in range(i):
        print('*',end=' ')
    print()

        1 
      1 2 
    1 2 3 
  1 2 3 4 
1 2 3 4 5 
        * 
      * * 
    * * * 
  * * * * 
* * * * * 


# 17th july 